apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodefarm
  labels:
    app: frontend-nodefarm
spec:
  template:
    metadata:
      labels:
        app: frontend-nodefarm
    spec:
      containers:
      - name: nodefarm-cont
        image: nds90/nodefarm-image:74da4833d74b90e2633272d82da37512b66c9e6c
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nodefarm