apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodefarm
  labels:
    app: frontend-nodefarm
spec:
  template:
    metadata:
      labels:
        app: frontend-nodefarm
    spec:
      containers:
      - name: nodefarm-cont
        image: nds90/nodefarm-image:b40186494f2cae7d0477c22d2e1505d84f7af627
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nodefarm