apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodefarm
  labels:
    app: frontend-nodefarm
spec:
  template:
    metadata:
      labels:
        app: frontend-nodefarm
    spec:
      containers:
      - name: nodefarm-cont
        image: nds90/nodefarm-image:fee299dcf835519ccd9dc69c3ebca66746be4f25
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nodefarm