apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodefarm
  labels:
    app: deployment-nodefarm
spec:
  template:
    metadata:
      labels:
        app: nodefarm-pod
    spec:
      containers:
      - name: nodefarm-cont
        image: nds90/nodefarm-image:f15233fe2f449c89c58462acb85d4a853d64f01f
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: nodefarm-js