apiVersion: apps/v1 #for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: deployment-nodefarm
spec:
  template:
    metadata:
      labels:
        app: nodefarm-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    spec:
      containers:
      - name: nodefarm-cont
        image: nds90/nodefarm-image:f15233fe2f449c89c58462acb85d4a853d64f01f
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: nodefarm-js