apiVersion: v1
kind: Service
metadata:
  name: nodefarm-svc
spec:
  type: LoadBalancer
  selector:
    app: nodefarm-js
  ports:
  - port: 3110
    protocol: TCP
    targetPort: 8000
    nodePort: 31230