apiVersion: v1
kind: Service
metadata:
  name: nodefarm-svc
  labels:
    app: frontend-nodefarm
spec:
  selector:
    app: nodefarm-js
  type: LoadBalancer
  ports:
    - port: 3110
      targetPort: 8000
      nodePort: 31230